import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Roboto, Exo, Space_Grotesk } from "next/font/google";
import "./globals.css";

import StoreProvider from "./global/storeProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ['400', '600'],
 subsets: ['latin'],
 display: 'swap',
});

const roboto = Roboto({
 weight: ['400', '700'],
 subsets: ['latin'],
 display: 'swap',
});

const exo = Exo({
 weight: ['400', '700'],
 subsets: ['latin'],
 display: 'swap',
});
const groteks = Space_Grotesk({
 weight: ['400', '700'],
 subsets: ['latin'],
 display: 'swap',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <StoreProvider>
     <html className={`${geistMono.variable}, ${groteks.className}`} lang="en">
     
          <body className="md:px-[200px] px-[25px] min-h-screen" >
       <div>
         {children}
       </div>
      </body>
     
    
    </html>
  </StoreProvider>
   
    
   
  );
}
